### ISSUE TITLE
매 시간마다 자동으로 체크 후 이미지 저장

### ISSUE THREAD

**Issue by ilsubyeega** [roian6/SelfCheckApp#1]
안녕하세요! "1초 자가진단"앱을 오늘 깔아봐서 아직 사용는 못해보았으나, 이 기능이 있으면 편해질것 같아서 혹시 추가가 되는지 이슈 날립니다.
_귀차니즘이 있는분들(접니다)_ 을 위해 앱에서 매일 지정된 시간에 자가진단 후 해당 결과화면을 이미지로 저장하게끔 되면 좋아 보입니다.

**Comment by roian6** [comment]
안녕하세요! 친절한 피드백 감사드립니다. 다만 해당 기능을 구현하는 데 있어서, 몇 가지 어려운 점이 있을 것 같습니다.

1. 안드로이드 운영체제의 특성 상, 특정 시간에 작업을 실행하는 기능을 구현하는 데는 상당히 큰 개발 비용이 소모됩니다.
(OS 버전도 많이 타고, 고려해야 할 변수도 많습니다..ㅠㅠ)

2. 해당 앱은 자가진단의 자체의 본질을 흐리지 않기 위해, "증상이 없을 때만 실행할 것" 을 명시하고 있습니다. 따라서 진단 예약은 이러한 내용에 다소 위반되는 기능일 수 있을 것 같습니다.

2번과 같은 이유로 권장드리진 않지만, 진단 예약이 꼭 필요하다면 빅스비 루틴 등의 기능을 활용하는 것도 하나의 방법이 될 수 있을 것 같습니다!

확인하시고 답장 주시면 이슈 close 진행하겠습니다!

**Comment by ilsubyeega** [comment]
> 안녕하세요! 친절한 피드백 감사드립니다. 다만 해당 기능을 구현하는 데 있어서, 몇 가지 어려운 점이 있을 것 같습니다.
> 
> 1. 안드로이드 운영체제의 특성 상, 특정 시간에 작업을 실행하는 기능을 구현하는 데는 상당히 큰 개발 비용이 소모됩니다.
> (OS 버전도 많이 타고, 고려해야 할 변수도 많습니다..ㅠㅠ)
> 
> 2. 해당 앱은 자가진단의 자체의 본질을 흐리지 않기 위해, "증상이 없을 때만 실행할 것" 을 명시하고 있습니다. 따라서 진단 예약은 이러한 내용에 다소 위반되는 기능일 수 있을 것 같습니다.
> 
> 2번과 같은 이유로 권장드리진 않지만, 진단 예약이 꼭 필요하다면 빅스비 루틴 등의 기능을 활용하는 것도 하나의 방법이 될 수 있을 것 같습니다!
> 
> 확인하시고 답장 주시면 이슈 close 진행하겠습니다!

확인했습니다! 답변해주셔서 감사합니다!
